### PR TITLE
Clean project

### PR DESCRIPTION
**Pull request by nuno-agostinho**
Fix typos, delete files not needed in the project and ignore the files .Rhistory, .Rapp.history, .RData and .DS_Store from the repository.

### CODE REVIEW

**Comment by nuno-agostinho** [comment]
The Travis-CI build is failing, yet I don't get failing errors when running the tests using testthat in my computer… Do you know why is this happening?

**Comment by ivan-krukov** [comment]
Looks like the failure is caused by GITSIC results not downloading:

https://travis-ci.org/mariodeng/FirebrowseR/builds/128296322#L1903

**Comment by ivan-krukov** [comment]
Looks great!

**Comment by nuno-agostinho** [comment]
Fortunately there was yet an unneeded file that could trigger the Travis-CI because I didn't know how to trigger it after the error. :stuck_out_tongue:

**Comment by mariodeng** [comment]
I pulled your suggestions into the master. But still, there is error with travis ci. I am currently skipping the test (online at travis) and try to identify what's causing the issues on another branch...

**Pull request merged**
